import { Inter } from "next/font/google";
import "./Styles/style.scss";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import Home from "./Home/page";
import Provider from "./components/Context/contextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "audio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <Provider>
            <Navbar />
              {children}
            <Footer />
          </Provider>
        </body>
      </html>
    </>
  );
}
